### ISSUE TITLE
Every 'failure_app' is called

### ISSUE THREAD

**Issue by BorisBresciani** [hassox/warden#148] opened 2017-05-30 18:31 UTC
Hello,

I do not understand why when I do:

`render json: {data: 'Error page'}, status: :unauthorized`

Is my failure app called? I can not render a `render json: data, status: :unauthorized` without call `failure_app` ?

My conf:

```ruby
    config.middleware.use Warden::Manager do |manager|
      manager.default_scope = :user
      manager.default_strategies :authentication_token
      manager.failure_app = ::UnauthorizedController
    end
```

UnauthorizedController:

```ruby
class UnauthorizedController < ActionController::Metal
  def self.call(env)
    @respond ||= action(:respond)
    @respond.call(env)
  end

  def respond
    self.response_body = _data.to_json
    self.content_type = 'application/json'
    self.status = :unauthorized
  end

  private
    def _message
      request.env['warden'].message
    end

    def _data
      ::ErrorTypeSerializer.serialize(_message.present? ? _message : 'INVALID_HEADER')
    end
end
```

Thx !

**Comment by jsmestad** [comment] 2017-06-07 20:44
I am not 100% familiar with the current `ActionController::Metal` API, but what your looking to return from a Rack is:

```ruby
class UnauthorizedController
  def call(env)
    [401, {"Content-Type" => "text/html"}, ["Unauthorized"]]
  end
end
```

If you map this to `ActionController::Metal` the failure app should work as intended.

**Comment by jsmestad** [comment] 2017-09-19 17:21
Closing. Let us know if that did not solve your issue.

**Closed by jsmestad** 2017-09-19 17:21 UTC
