### ISSUE TITLE
Rails 5 RuntimeError: can't modify frozen Hash

### ISSUE THREAD

**Issue by stevenspiel** [hassox/warden#147] opened 2017-05-12 19:33 UTC
I just upgraded to Rails 5 and I'm getting an error that stems from [this line](https://github.com/hassox/warden/blob/master/lib/warden/proxy.rb#L175):

```rb
options = env[ENV_SESSION_OPTIONS]
options[:renew] = true if options
```

`env[ENV_SESSION_OPTIONS]` is a frozen hash, and so it cannot be modified.

Using version `1.2.7` with Rails `5.0.0` and Ruby `2.3.1`

**Comment by stevenspiel** [comment] 2017-05-12 19:52
Changing rack version from `2.0.2` to `2.0.1` fixed it.

**Comment by zeitnot** [comment] 2017-05-25 14:40
I have the same problem and @stevenspiel's solution worked. But this is not a proper solution.

**Comment by md5** [comment] 2017-06-06 00:41
See https://github.com/rack/rack/pull/1110 for the change that freezes the `DEFAULT_OPTIONS` hash in Rack.

See https://github.com/rails/rails/pull/26442 for the Rails 5.1 fix that avoids assigning `DEFAULT_OPTIONS` to `request.session_options` in `ActionController::TestSession`. The fix has been backported to the Rails 5.0 branch, but it has not been included in a 5.0 release.

**Comment by whithub** [comment] 2017-06-18 17:57
@md5 Does that mean I can close out this ticket or is it still an issue?

**Comment by md5** [comment] 2017-06-30 23:20
@whithub I believe it's still an issue.

I *think* the fix for `warden` is to do something like this:

```diff
diff --git a/lib/warden/proxy.rb b/lib/warden/proxy.rb
index b6cc857..86697df 100644
--- a/lib/warden/proxy.rb
+++ b/lib/warden/proxy.rb
@@ -172,7 +172,7 @@ module Warden
 
       if opts[:store] != false && opts[:event] != :fetch
         options = env[ENV_SESSION_OPTIONS]
-        options[:renew] = true if options
+        env[ENV_SESSION_OPTIONS] = options.merge(renew: true) if options
         session_serializer.store(user, scope)
       end
```

**Comment by HeidiHansen** [comment] 2017-09-14 02:31
Could this fix be merged?  I'm having this issue.  =(

**Comment by md5** [comment] 2017-09-27 03:47
@HeidiHansen There isn't a PR. I haven't actually tested my proposed fix since I haven't encountered this problem recently.

Looking at that patch again, it should probably check if the original options are `frozen?` and re-freeze the merged `Hash`.

**Comment by jsmestad** [comment] 2017-09-27 07:35
Yeah we could use a hand creating a test case to re-produce the issue. It is proving more time consuming than we'd anticipated. @HeidiHansen @md5 if you guys have the time to get a failure for us to work with.

**Comment by md5** [comment] 2017-09-28 05:28
https://github.com/hassox/warden/pull/161

**Closed** 2017-09-28 19:17 UTC

**Comment by whithub** [comment] 2017-09-28 19:20
Thank you @md5 for all your help and patience on this issue!

**Comment by francisnkhata** [comment] 2023-12-17 12:04
Still facing the same issue when trying to migrate/initialise database.
`FrozenError: can't modify frozen Hash
/usr/share/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.4.6/lib/active_support/deprecation/method_wrappers.rb:54:in `delete'
`
On rails 5.2.4.3

Getting the following

+ export RAILS_ENV=development
+ RAILS_ENV=development
+ rails db:environment:set RAILS_ENV=development
rails aborted!
**FrozenError: can't modify frozen Hash**
/usr/share/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.4.6/lib/active_support/deprecation/method_wrappers.rb:54:in `delete'
/usr/share/rvm/gems/ruby-2.5.3/gems/activesupport-5.2.4.6/lib/active_support/deprecation/method_wrappers.rb:54:in `deprecate_methods'
/usr/share/rvm/gems/ruby-2.5.3/gems/rswag-api-2.13.0/lib/rswag/api.rb:32:in `<module:Api>'
/usr/share/rvm/gems/ruby-2.5.3/gems/rswag-api-2.13.0/lib/rswag/api.rb:6:in `<module:Rswag>'
/usr/share/rvm/gems/ruby-2.5.3/gems/rswag-api-2.13.0/lib/rswag/api.rb:5:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.5.3/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/share/rvm/gems/ruby-2.5.3/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/var/www/BHT-EMR-API/config/application.rb:18:in `<top (required)>'
/var/www/BHT-EMR-API/Rakefile:4:in `require_relative'
/var/www/BHT-EMR-API/Rakefile:4:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.5.3/gems/railties-5.2.4.6/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/usr/share/rvm/gems/ruby-2.5.3/gems/railties-5.2.4.6/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/share/rvm/gems/ruby-2.5.3/gems/railties-5.2.4.6/lib/rails/command.rb:48:in `invoke'
/usr/share/rvm/gems/ruby-2.5.3/gems/railties-5.2.4.6/lib/rails/commands.rb:18:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.5.3/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/share/rvm/gems/ruby-2.5.3/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/var/www/BHT-EMR-API/bin/rails:9:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.5.3/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/usr/share/rvm/gems/ruby-2.5.3/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/usr/share/rvm/gems/ruby-2.5.3/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/usr/share/rvm/gems/ruby-2.5.3/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/usr/share/rvm/gems/ruby-2.5.3/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/usr/share/rvm/gems/ruby-2.5.3/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/usr/share/rvm/gems/ruby-2.5.3/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/var/www/BHT-EMR-API/bin/spring:15:in `require'
/var/www/BHT-EMR-API/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
**LoadError: cannot load such file -- rswag-api**
